// Writes website/changelog.html from store/releases.json and the release
// notes in store/<locale>/changelogs/, so the website never keeps its own
// copy of them. Run from the project root after bumping the version:
//   dart run tool/website_changelog.dart
// test/store/website_changelog_test.dart fails while the page is stale.
import 'dart:convert';
import 'dart:io';

const pagePath = 'website/changelog.html';

const _monthsId = [
  'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', //
  'Agustus', 'September', 'Oktober', 'November', 'Desember',
];
const _monthsEn = [
  'January', 'February', 'March', 'April', 'May', 'June', 'July', //
  'August', 'September', 'October', 'November', 'December',
];

String _escape(String s) => const HtmlEscape(HtmlEscapeMode.element).convert(s);
String _attr(String s) => const HtmlEscape(HtmlEscapeMode.attribute).convert(s);

/// A release note: "- " or "• " lines become a list, other lines paragraphs.
List<(bool, String)> _notes(String text) => [
  for (final line in const LineSplitter().convert(text))
    if (line.trim().isNotEmpty)
      switch (line.trim()) {
        final l when l.startsWith('- ') || l.startsWith('• ') => (
          true,
          l.substring(2).trim(),
        ),
        final l => (false, l),
      },
];

/// Indonesian in the HTML, English in data-en, as on the rest of the site.
String _bilingual(List<(bool, String)> id, List<(bool, String)> en) {
  if (id.length != en.length) {
    throw StateError('Release notes differ in length between id and en-US');
  }
  final out = StringBuffer();
  var inList = false;
  for (var i = 0; i < id.length; i++) {
    final (item, idText) = id[i];
    final enText = en[i].$2;
    if (item && !inList) out.writeln('      <ul>');
    if (!item && inList) out.writeln('      </ul>');
    inList = item;
    final tag = item ? 'li' : 'p';
    out.writeln(
      '${item ? '        ' : '      '}<$tag data-en="${_attr(enText)}">'
      '${_escape(idText)}</$tag>',
    );
  }
  if (inList) out.writeln('      </ul>');
  return out.toString();
}

String buildChangelogPage({String root = '.'}) {
  final releases =
      (jsonDecode(File('$root/store/releases.json').readAsStringSync())
              as Map<String, dynamic>)['releases']
          as List;
  final entries = StringBuffer();
  for (final release in releases.reversed) {
    final r = release as Map<String, dynamic>;
    final build = r['build'] as int;
    final version = r['version'] as String;
    final date = DateTime.parse(r['date'] as String);
    String notes(String locale) =>
        File('$root/store/$locale/changelogs/$build.txt').readAsStringSync();
    final dateId = '${date.day} ${_monthsId[date.month - 1]} ${date.year}';
    final dateEn = '${date.day} ${_monthsEn[date.month - 1]} ${date.year}';
    entries.write('''
    <article class="release" id="build-$build">
      <h2>$version <span class="build" data-en="build $build">build $build</span></h2>
      <p class="updated"><time datetime="${r['date']}" data-en="$dateEn">$dateId</time></p>
${_bilingual(_notes(notes('id')), _notes(notes('en-US')))}    </article>
''');
  }
  return '''
<!doctype html>
<!-- Generated by tool/website_changelog.dart from store/; do not edit. -->
<html lang="id">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title data-en="What's new · Coba Lagi">Yang baru · Coba Lagi</title>
  <meta name="description" content="Catatan rilis Coba Lagi: apa yang berubah di setiap versi.">
  <meta name="theme-color" content="#00a6a6">
  <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Ccircle cx='32' cy='34' r='24' fill='%23ff7a59'/%3E%3Cpath d='M32 4l8 10H24z' fill='%23ff7a59'/%3E%3Ccircle cx='24' cy='26' r='6' fill='%23fff'/%3E%3Ccircle cx='40' cy='26' r='6' fill='%23fff'/%3E%3Ccircle cx='24' cy='24' r='3' fill='%23263238'/%3E%3Ccircle cx='40' cy='24' r='3' fill='%23263238'/%3E%3C/svg%3E">
  <link rel="stylesheet" href="site.css">
</head>
<body>
  <header>
    <div class="wrap bar">
      <a class="brand" href="index.html" data-keep-lang aria-label="Coba Lagi">
        <svg viewBox="0 0 64 64" aria-hidden="true">
          <circle cx="33" cy="37" r="23" fill="#000" opacity=".12"/>
          <circle cx="32" cy="34" r="23" fill="#ff7a59"/>
          <circle cx="32" cy="41" r="11" fill="#ffb199"/>
          <path d="M32 5l8 10H24z" fill="#ff7a59"/>
          <circle cx="24" cy="26" r="6" fill="#fff"/><circle cx="40" cy="26" r="6" fill="#fff"/>
          <circle cx="24" cy="24" r="3" fill="#263238"/><circle cx="40" cy="24" r="3" fill="#263238"/>
        </svg>
        Coba Lagi
      </a>
      <nav aria-label="Menu">
        <a href="index.html" data-keep-lang data-en="Home">Beranda</a>
        <a class="github" href="https://github.com/ardeman/project_cobalagi_flutter" aria-label="Kode sumber di GitHub" data-en-label="Source code on GitHub">
          <svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"/></svg>
        </a>
        <button class="lang" id="lang" type="button" aria-label="Switch to English">EN</button>
      </nav>
    </div>
  </header>

  <main class="wrap doc">
    <h1 data-en="What's new">Yang baru</h1>
    <p class="updated" data-en="What changed in each version of Coba Lagi. The newest is at the top.">Apa yang berubah di setiap versi Coba Lagi. Yang terbaru ada di paling atas.</p>
${entries.toString().trimRight()}
  </main>

  <footer>
    <div class="wrap foot">
      <p>© 2026 Ardeman · Coba Lagi · <a href="https://github.com/ardeman/project_cobalagi_flutter">GitHub</a></p>
      <p><a href="index.html" data-keep-lang data-en="Back to home">Kembali ke beranda</a></p>
    </div>
  </footer>

  <script src="site.js"></script>
</body>
</html>
''';
}

void main() {
  File(pagePath).writeAsStringSync(buildChangelogPage());
  stdout.writeln('Wrote $pagePath');
}
