// Writes website/changelog.html from store/releases.json and the release
// notes in store/<locale>/changelogs/, so the website never keeps its own
// copy of them. Run from the project root after bumping the version:
//   dart run tool/website_changelog.dart
// test/store/website_changelog_test.dart fails while the page is stale.
import 'dart:convert';
import 'dart:io';

const pagePath = 'website/changelog.html';

const _monthsId = [
  'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', //
  'Agustus', 'September', 'Oktober', 'November', 'Desember',
];
const _monthsEn = [
  'January', 'February', 'March', 'April', 'May', 'June', 'July', //
  'August', 'September', 'October', 'November', 'December',
];

String _escape(String s) => const HtmlEscape(HtmlEscapeMode.element).convert(s);
String _attr(String s) => const HtmlEscape(HtmlEscapeMode.attribute).convert(s);

/// A release note: "- " or "• " lines become a list, other lines paragraphs.
List<(bool, String)> _notes(String text) => [
  for (final line in const LineSplitter().convert(text))
    if (line.trim().isNotEmpty)
      switch (line.trim()) {
        final l when l.startsWith('- ') || l.startsWith('• ') => (
          true,
          l.substring(2).trim(),
        ),
        final l => (false, l),
      },
];

/// Indonesian in the HTML, English in data-en, as on the rest of the site.
String _bilingual(List<(bool, String)> id, List<(bool, String)> en) {
  if (id.length != en.length) {
    throw StateError('Release notes differ in length between id and en-US');
  }
  final out = StringBuffer();
  var inList = false;
  for (var i = 0; i < id.length; i++) {
    final (item, idText) = id[i];
    final enText = en[i].$2;
    if (item && !inList) out.writeln('      <ul>');
    if (!item && inList) out.writeln('      </ul>');
    inList = item;
    final tag = item ? 'li' : 'p';
    out.writeln(
      '${item ? '        ' : '      '}<$tag data-en="${_attr(enText)}">'
      '${_escape(idText)}</$tag>',
    );
  }
  if (inList) out.writeln('      </ul>');
  return out.toString();
}

/// The site's shared header, taken from the privacy page so every page
/// has the same menu.
String _header(String root) {
  final privacy = File('$root/website/privacy.html').readAsStringSync();
  final start = privacy.indexOf('  <header>\n');
  final end = privacy.indexOf('  </header>\n') + '  </header>\n'.length;
  return privacy.substring(start, end);
}

/// The site's shared footer, also taken from the privacy page.
String _footer(String root) {
  final privacy = File('$root/website/privacy.html').readAsStringSync();
  final start = privacy.indexOf('  <footer>\n');
  final end = privacy.indexOf('  </footer>\n') + '  </footer>\n'.length;
  return privacy.substring(start, end);
}

String buildChangelogPage({String root = '.'}) {
  final releases =
      (jsonDecode(File('$root/store/releases.json').readAsStringSync())
              as Map<String, dynamic>)['releases']
          as List;
  final entries = StringBuffer();
  for (final release in releases.reversed) {
    final r = release as Map<String, dynamic>;
    final build = r['build'] as int;
    final version = r['version'] as String;
    final date = DateTime.parse(r['date'] as String);
    String notes(String locale) =>
        File('$root/store/$locale/changelogs/$build.txt').readAsStringSync();
    final dateId = '${date.day} ${_monthsId[date.month - 1]} ${date.year}';
    final dateEn = '${date.day} ${_monthsEn[date.month - 1]} ${date.year}';
    entries.write('''
    <article class="release" id="build-$build">
      <h2>$version <span class="build" data-en="build $build">build $build</span></h2>
      <p class="updated"><time datetime="${r['date']}" data-en="$dateEn">$dateId</time></p>
${_bilingual(_notes(notes('id')), _notes(notes('en-US')))}    </article>
''');
  }
  return '''
<!doctype html>
<!-- Generated by tool/website_changelog.dart from store/; do not edit. -->
<html lang="id">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title data-en="What's new · Coba Lagi">Yang baru · Coba Lagi</title>
  <meta name="description" content="Catatan rilis Coba Lagi: apa yang berubah di setiap versi.">
  <meta name="theme-color" content="#00a6a6">
  <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Ccircle cx='32' cy='34' r='24' fill='%23ff7a59'/%3E%3Cpath d='M32 4l8 10H24z' fill='%23ff7a59'/%3E%3Ccircle cx='24' cy='26' r='6' fill='%23fff'/%3E%3Ccircle cx='40' cy='26' r='6' fill='%23fff'/%3E%3Ccircle cx='24' cy='24' r='3' fill='%23263238'/%3E%3Ccircle cx='40' cy='24' r='3' fill='%23263238'/%3E%3C/svg%3E">
  <link rel="stylesheet" href="site.css">
</head>
<body>
${_header(root)}
  <main class="wrap doc">
    <h1 data-en="What's new">Yang baru</h1>
    <p class="updated" data-en="What changed in each version of Coba Lagi. The newest is at the top.">Apa yang berubah di setiap versi Coba Lagi. Yang terbaru ada di paling atas.</p>
${entries.toString().trimRight()}
  </main>

${_footer(root)}
  <script src="site.js"></script>
</body>
</html>
''';
}

void main() {
  File(pagePath).writeAsStringSync(buildChangelogPage());
  stdout.writeln('Wrote $pagePath');
}
